# Generated by Django 4.1.13 on 2026-07-23 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bones', '0014_baseline_audited_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEntityImageTarget',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('entity_type', models.CharField(choices=[('transect', 'Transect'), ('occurrence', 'Occurrence'), ('instance', 'Instance')], max_length=20)),
                ('entity_id', models.CharField(max_length=80)),
                ('linked_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bones.entityimage')),
                ('linked_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical entity image target',
                'verbose_name_plural': 'historical entity image targets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EntityImageTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('transect', 'Transect'), ('occurrence', 'Occurrence'), ('instance', 'Instance')], max_length=20)),
                ('entity_id', models.CharField(max_length=80)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='bones.entityimage')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bones_image_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('linked_at',),
            },
        ),
        migrations.AddIndex(
            model_name='entityimagetarget',
            index=models.Index(fields=['entity_type', 'entity_id'], name='bones_image_target_entity_idx'),
        ),
        migrations.AddConstraint(
            model_name='entityimagetarget',
            constraint=models.UniqueConstraint(fields=('image', 'entity_type', 'entity_id'), name='bones_image_target_unique'),
        ),
    ]
