# Generated by Django 4.1.13 on 2026-07-23 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bones', '0016_populate_image_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceDeletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=200)),
                ('transect_uid', models.IntegerField(db_index=True)),
                ('transect_date', models.DateField(blank=True, null=True)),
                ('occurrence_id', models.IntegerField(db_index=True)),
                ('occurrence_number', models.IntegerField()),
                ('instance_number', models.IntegerField(db_index=True)),
                ('reason', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('workflow_count', models.PositiveIntegerField(default=0)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('image_link_count', models.PositiveIntegerField(default=0)),
                ('image_file_count', models.PositiveIntegerField(default=0)),
                ('workflow_snapshot', models.JSONField(blank=True, default=list)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bones_instance_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-deleted_at',),
                'permissions': (('delete_completed_instance', 'Can delete completed instances'),),
            },
        ),
        migrations.CreateModel(
            name='HistoricalInstanceDeletion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('template_name', models.CharField(max_length=200)),
                ('transect_uid', models.IntegerField(db_index=True)),
                ('transect_date', models.DateField(blank=True, null=True)),
                ('occurrence_id', models.IntegerField(db_index=True)),
                ('occurrence_number', models.IntegerField()),
                ('instance_number', models.IntegerField(db_index=True)),
                ('reason', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('workflow_count', models.PositiveIntegerField(default=0)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('image_link_count', models.PositiveIntegerField(default=0)),
                ('image_file_count', models.PositiveIntegerField(default=0)),
                ('workflow_snapshot', models.JSONField(blank=True, default=list)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical instance deletion',
                'verbose_name_plural': 'historical instance deletions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='instancedeletion',
            index=models.Index(fields=['occurrence_id', 'instance_number'], name='bones_deleted_instance_idx'),
        ),
    ]
