# Generated by Django 4.1.13 on 2026-07-23 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bones', '0017_instance_deletion_audit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancedeletion',
            options={'ordering': ('-deleted_at',), 'permissions': (('delete_completed_instance', 'Can delete completed instances'), ('restore_completed_instance', 'Can restore completed instances'))},
        ),
        migrations.AddField(
            model_name='entityimage',
            name='archived_by_deletion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_images', to='bones.instancedeletion'),
        ),
        migrations.AddField(
            model_name='historicalentityimage',
            name='archived_by_deletion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bones.instancedeletion'),
        ),
        migrations.AddField(
            model_name='historicalinstancedeletion',
            name='image_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='historicalinstancedeletion',
            name='response_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='historicalinstancedeletion',
            name='restoration_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalinstancedeletion',
            name='restoration_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalinstancedeletion',
            name='restoration_status',
            field=models.CharField(db_index=True, default='deleted', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalinstancedeletion',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinstancedeletion',
            name='restored_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instancedeletion',
            name='image_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instancedeletion',
            name='response_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instancedeletion',
            name='restoration_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instancedeletion',
            name='restoration_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='instancedeletion',
            name='restoration_status',
            field=models.CharField(db_index=True, default='deleted', max_length=20),
        ),
        migrations.AddField(
            model_name='instancedeletion',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instancedeletion',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bones_instance_restorations', to=settings.AUTH_USER_MODEL),
        ),
    ]
