# Generated by Django 4.1.13 on 2026-07-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bones', '0018_restorable_instance_deletions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcompletedresponse',
            name='id',
            field=models.IntegerField(db_column='ID', db_index=True),
        ),
    ]
