# Generated by Django 4.1.13 on 2026-07-31 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bones', '0021_transectdeletion_historicaltransectdeletion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MNIElementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('divisor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('paired', models.BooleanField(default=False)),
                ('excluded', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('reviewed', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'MNI element rule',
                'verbose_name_plural': 'MNI element rules',
                'ordering': ('canonical_name',),
            },
        ),
        migrations.CreateModel(
            name='MNITaxonRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_alias', models.CharField(max_length=120, unique=True)),
                ('canonical_label', models.CharField(max_length=120)),
                ('default_excluded', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'MNI taxon rule',
                'verbose_name_plural': 'MNI taxon rules',
                'ordering': ('canonical_label', 'source_alias'),
            },
        ),
    ]
