# Generated by Django 4.1.13 on 2026-08-01 16:45

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bones', '0023_seed_mni_reference_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceDeletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_id', models.IntegerField(db_index=True)),
                ('occurrence_number', models.IntegerField()),
                ('transect_uid', models.IntegerField(db_index=True)),
                ('template_name', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('workflow_count', models.PositiveIntegerField(default=0)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('snapshot', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bones_occurrence_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-deleted_at',),
                'permissions': (('delete_completed_occurrence', 'Can delete completed occurrences'),),
            },
        ),
        migrations.CreateModel(
            name='HistoricalOccurrenceDeletion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('occurrence_id', models.IntegerField(db_index=True)),
                ('occurrence_number', models.IntegerField()),
                ('transect_uid', models.IntegerField(db_index=True)),
                ('template_name', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('workflow_count', models.PositiveIntegerField(default=0)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('snapshot', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical occurrence deletion',
                'verbose_name_plural': 'historical occurrence deletions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='entityimage',
            name='archived_by_occurrence_deletion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_images', to='bones.occurrencedeletion'),
        ),
        migrations.AddField(
            model_name='historicalentityimage',
            name='archived_by_occurrence_deletion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bones.occurrencedeletion'),
        ),
    ]
