version: 2

updates:
  - package-ecosystem: pip
    directory: /app
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - dependencies
      - python
    commit-message:
      prefix: deps
    ignore:
      - dependency-name: Django
        update-types:
          - version-update:semver-major
    groups:
      python-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /app
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 2
    labels:
      - dependencies
    commit-message:
      prefix: docker
    ignore:
      - dependency-name: python
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    groups:
      docker-images:
        patterns:
          - "*"
